/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import java.awt.Dialog;
import java.io.File;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zapia
 */
public class LimpiezaPorTamanio extends javax.swing.JDialog {

    private File[] ficherosEscaneados;
    private LogicaMetodos logicaMetodos;
    private String rutaSeleccionada;

    /**
     * Creates new form LimpiezaPorTamanio
     */
    public LimpiezaPorTamanio(Dialog owner, boolean modal, LogicaMetodos logicaMetodos, String rutaSeleccionada) {
        super(owner, modal);
        initComponents();
        this.logicaMetodos = logicaMetodos;
        this.rutaSeleccionada = rutaSeleccionada;
    }

    private void rellenarTablaFicherosABorrar() {
        String[] columnas = {"Fichero", "Ruta", "Peso(MB)"};
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        for (File fichero : ficherosEscaneados) {

            String[] a = new String[3];
            a[0] = fichero.getName();
            a[1] = fichero.getAbsolutePath();
            a[2] = Long.toString(fichero.length() / 1048576);

            dtm.addRow(a);
        }
        jTableFichero.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLimpieza = new javax.swing.JLabel();
        jLabelTamanio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFichero = new javax.swing.JTable();
        jComboBoxTamanios = new javax.swing.JComboBox<>();
        jToggleButtonEscanearTamanios = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButtonCerrar = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelLimpieza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLimpieza.setForeground(new java.awt.Color(102, 102, 102));
        jLabelLimpieza.setText("Limpieza por Tamaño");

        jLabelTamanio.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTamanio.setText("Tamaño:");

        jTableFichero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fichero", "Ruta", "Peso(MB)"
            }
        ));
        jScrollPane1.setViewportView(jTableFichero);

        jComboBoxTamanios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<700MB", "700MB-10GB", ">10GB" }));
        jComboBoxTamanios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamaniosActionPerformed(evt);
            }
        });

        jToggleButtonEscanearTamanios.setText("Escanear");
        jToggleButtonEscanearTamanios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonEscanearTamaniosActionPerformed(evt);
            }
        });

        jToggleButton2.setText("Borrar todo");
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });

        jToggleButton3.setText("Borrar seleccionados");

        jToggleButtonCerrar.setText("Cerrar");
        jToggleButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxTamanios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jToggleButtonEscanearTamanios, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(89, 89, 89))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabelLimpieza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(95, 95, 95)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jToggleButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jToggleButtonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLimpieza)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTamanio)
                    .addComponent(jComboBoxTamanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jToggleButtonEscanearTamanios))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jToggleButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToggleButton3)
                .addGap(18, 18, 18)
                .addComponent(jToggleButtonCerrar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTamaniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamaniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamaniosActionPerformed

    private void jToggleButtonEscanearTamaniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonEscanearTamaniosActionPerformed
        
        ficherosEscaneados = logicaMetodos.escanearFicherosPorTamanio(jComboBoxTamanios.getSelectedIndex(), rutaSeleccionada);
        System.out.println("Escaneo Completado");
        rellenarTablaFicherosABorrar();
    }//GEN-LAST:event_jToggleButtonEscanearTamaniosActionPerformed

    private void jToggleButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCerrarActionPerformed
        dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButtonCerrarActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jToggleButton2ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBoxTamanios;
    private javax.swing.JLabel jLabelLimpieza;
    private javax.swing.JLabel jLabelTamanio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFichero;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButtonCerrar;
    private javax.swing.JToggleButton jToggleButtonEscanearTamanios;
    // End of variables declaration//GEN-END:variables
}
