/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Logica;

import java.awt.Dialog;

/**
 *
 * @author alumnop
 */
public class LimpiezaPorTipo extends javax.swing.JDialog {

    private LogicaMetodos logicaMetodos;
    private String rutaSeleccionada;

    /**
     * Creates new form LimpiezaPorTipo
     */
    public LimpiezaPorTipo() {
        initComponents();
    }

    public LimpiezaPorTipo(Dialog owner, boolean modal, LogicaMetodos logicaMetodos, String rutaSeleccionada) {
        super(owner, modal);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabelTipoFichero = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButtonEscanear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Limpieza por Tipo");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(114, 12, -1, -1));

        jLabelTipoFichero.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTipoFichero.setText("Tipo de fichero:");
        jPanel1.add(jLabelTipoFichero, new org.netbeans.lib.awtextra.AbsoluteConstraints(12, 57, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Imágenes", "Vídeos", "Audio", "Texto" }));
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(134, 52, -1, -1));

        jButtonEscanear.setText("Escanear");
        jPanel1.add(jButtonEscanear, new org.netbeans.lib.awtextra.AbsoluteConstraints(243, 52, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonEscanear;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelTipoFichero;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
