/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.LogicaMetodos;
import java.awt.Dialog;
import java.io.File;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zapia
 */
public class ComprimirCarpetas extends javax.swing.JDialog {

    private LogicaMetodos logicaMetodos;
    private File[] ficherosEscaneados;
    private File carpetaEscogidaParaComprimir;
    private File carpetaDestino;

    /**
     * Creates new form ComprimirCarpetas
     */
    public ComprimirCarpetas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(this);
    }

    public ComprimirCarpetas(Dialog owner, boolean modal, LogicaMetodos logicaMetodos) {
        super(owner, modal);
        this.logicaMetodos = logicaMetodos;
        initComponents();
        this.setLocationRelativeTo(this);
    }

    private void rellenarTablaComprimir() {
        String[] columnas = {"Fichero", "Ruta", "Peso(MB)"};
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        for (File fichero : ficherosEscaneados) {
            String[] columnasInformacionDeFichero = new String[3];
            columnasInformacionDeFichero[0] = fichero.getName();
            columnasInformacionDeFichero[1] = fichero.getAbsolutePath();
            columnasInformacionDeFichero[2] = Long.toString(fichero.length() / 1048576);
            dtm.addRow(columnasInformacionDeFichero);
        }
        jTableComprimir.setModel(dtm);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelEscogeCarpetas = new javax.swing.JLabel();
        jLabelComprension = new javax.swing.JLabel();
        jButtonEscogeCarpeta = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableComprimir = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonCerrar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonEscogeDestino = new javax.swing.JButton();
        jTextFieldNombreZip = new javax.swing.JTextField();
        jButtonAccionComprimir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelEscogeCarpetas.setText("Escoge que carpeta vas a comprimir");

        jLabelComprension.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelComprension.setText("Comprimir Carpetas");

        jButtonEscogeCarpeta.setText("...");
        jButtonEscogeCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscogeCarpetaActionPerformed(evt);
            }
        });

        jTableComprimir.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Archivo", "Ruta", "Peso(MB)"
            }
        ));
        jScrollPane1.setViewportView(jTableComprimir);

        jLabel1.setText("Contenido de la carpeta escogida");

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jLabel2.setText("Escoge ruta de destino y nombre del archivo, el archivo se comprimira en .zip");

        jButtonEscogeDestino.setText("...");
        jButtonEscogeDestino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscogeDestinoActionPerformed(evt);
            }
        });

        jButtonAccionComprimir.setText("Comprimir");
        jButtonAccionComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAccionComprimirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(127, 127, 127)
                        .addComponent(jLabelComprension, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabelEscogeCarpetas)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonEscogeCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGap(118, 118, 118))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jButtonEscogeDestino, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextFieldNombreZip, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonAccionComprimir, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCerrar))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(94, 94, 94)))
                .addGap(37, 37, 37))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabelComprension)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelEscogeCarpetas)
                    .addComponent(jButtonEscogeCarpeta))
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonEscogeDestino)
                    .addComponent(jTextFieldNombreZip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonAccionComprimir)
                    .addComponent(jButtonCerrar))
                .addGap(83, 83, 83))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEscogeCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscogeCarpetaActionPerformed

        carpetaEscogidaParaComprimir = logicaMetodos.escogerDirectorio(this);
        ficherosEscaneados = logicaMetodos.listarArchivosRecursivamente(carpetaEscogidaParaComprimir.getAbsolutePath());
        rellenarTablaComprimir();
    }//GEN-LAST:event_jButtonEscogeCarpetaActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonEscogeDestinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscogeDestinoActionPerformed
        carpetaDestino = logicaMetodos.escogerDirectorio(this);
    }//GEN-LAST:event_jButtonEscogeDestinoActionPerformed

    private void jButtonAccionComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAccionComprimirActionPerformed
        try {
            logicaMetodos.comprimirCarpeta(carpetaDestino, carpetaDestino.getAbsolutePath() + "/" + jTextFieldNombreZip.getText(), carpetaEscogidaParaComprimir);
        } catch (Exception ex) {
            Logger.getLogger(ComprimirCarpetas.class.getName()).log(Level.SEVERE, null, ex);
        }
        JOptionPane.showMessageDialog(this, "Carpeta comprimida con éxito");
    }//GEN-LAST:event_jButtonAccionComprimirActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAccionComprimir;
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonEscogeCarpeta;
    private javax.swing.JButton jButtonEscogeDestino;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelComprension;
    private javax.swing.JLabel jLabelEscogeCarpetas;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableComprimir;
    private javax.swing.JTextField jTextFieldNombreZip;
    // End of variables declaration//GEN-END:variables
}
