/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.LogicaMetodos;
import java.awt.Dialog;
import java.io.File;
import java.util.Arrays;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author zapia
 */
public class LimpiezaPorTamanio extends javax.swing.JDialog {

    private File[] ficherosEscaneados;
    private LogicaMetodos logicaMetodos;
    private String rutaSeleccionada;
    private int opcionEscogida;

    /**
     * Creates new form LimpiezaPorTamanio
     */
    public LimpiezaPorTamanio(Dialog owner, boolean modal, LogicaMetodos logicaMetodos, String rutaSeleccionada) {
        super(owner, modal);
        initComponents();
        this.logicaMetodos = logicaMetodos;
        this.rutaSeleccionada = rutaSeleccionada;
    }

    private void rellenarTablaFicheros() {
        String[] columnas = {"Fichero", "Ruta", "Peso(MB)"};
        DefaultTableModel dtm = new DefaultTableModel(columnas, 0);
        for (File fichero : ficherosEscaneados) {

            String[] columnasInformacionDeFichero = new String[3];
            columnasInformacionDeFichero[0] = fichero.getName();
            columnasInformacionDeFichero[1] = fichero.getAbsolutePath();
            columnasInformacionDeFichero[2] = Long.toString(fichero.length() / 1048576);

            dtm.addRow(columnasInformacionDeFichero);
        }
        jTableFichero.setModel(dtm);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabelLimpieza = new javax.swing.JLabel();
        jLabelTamanio = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableFichero = new javax.swing.JTable();
        jComboBoxTamanios = new javax.swing.JComboBox<>();
        jToggleButtonCerrar = new javax.swing.JToggleButton();
        jButtonEscanear = new javax.swing.JButton();
        jButtonBorrarSeleccionados = new javax.swing.JButton();
        jButtonBorradoAbsoluto = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabelLimpieza.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabelLimpieza.setForeground(new java.awt.Color(102, 102, 102));
        jLabelLimpieza.setText("Limpieza por Tamaño");

        jLabelTamanio.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabelTamanio.setForeground(new java.awt.Color(102, 102, 102));
        jLabelTamanio.setText("Tamaño:");

        jTableFichero.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Fichero", "Ruta", "Peso(MB)"
            }
        ));
        jScrollPane1.setViewportView(jTableFichero);

        jComboBoxTamanios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "<1GB", "1-10GB", ">10GB" }));
        jComboBoxTamanios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTamaniosActionPerformed(evt);
            }
        });

        jToggleButtonCerrar.setText("Cerrar");
        jToggleButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButtonCerrarActionPerformed(evt);
            }
        });

        jButtonEscanear.setText("Escanear");
        jButtonEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscanearActionPerformed(evt);
            }
        });

        jButtonBorrarSeleccionados.setText("Borrar seleccionados");
        jButtonBorrarSeleccionados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorrarSeleccionadosActionPerformed(evt);
            }
        });

        jButtonBorradoAbsoluto.setText("Borrar todo");
        jButtonBorradoAbsoluto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonBorradoAbsolutoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabelTamanio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBoxTamanios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(18, 18, 18)
                                .addComponent(jButtonEscanear, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(75, 75, 75))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGap(96, 96, 96)
                                .addComponent(jLabelLimpieza, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGap(95, 95, 95)))
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(123, 123, 123)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jToggleButtonCerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorrarSeleccionados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonBorradoAbsoluto, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(96, 96, 96))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelLimpieza)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTamanio)
                    .addComponent(jComboBoxTamanios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonEscanear))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE)
                .addGap(32, 32, 32)
                .addComponent(jButtonBorradoAbsoluto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonBorrarSeleccionados)
                .addGap(11, 11, 11)
                .addComponent(jToggleButtonCerrar)
                .addGap(18, 18, 18))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTamaniosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTamaniosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTamaniosActionPerformed

    private void jToggleButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jToggleButtonCerrarActionPerformed

    private void jButtonEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscanearActionPerformed
        
        opcionEscogida = jComboBoxTamanios.getSelectedIndex();
        ficherosEscaneados = logicaMetodos.escanearFicherosPorTamanio(jComboBoxTamanios.getSelectedIndex(), rutaSeleccionada);
        JOptionPane.showMessageDialog(this, "Escaneo completado");
        rellenarTablaFicheros();
    }//GEN-LAST:event_jButtonEscanearActionPerformed

    private void jButtonBorrarSeleccionadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorrarSeleccionadosActionPerformed
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea eliminar los ficheros seleccionados?", "Eliminar ficheros seleccionados", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            int[] intFicherosSeleccionados = jTableFichero.getSelectedRows();
            File[] ficherosSeleccionados = new File[intFicherosSeleccionados.length];
            System.out.println("longitud: " + intFicherosSeleccionados.length);
            for (int contadorFicherosArray = 0; contadorFicherosArray < ficherosSeleccionados.length; contadorFicherosArray++) {
                ficherosSeleccionados[contadorFicherosArray] = ficherosEscaneados[intFicherosSeleccionados[contadorFicherosArray]];
            }
            logicaMetodos.borradoDeFicheros(ficherosSeleccionados, "FicherosBorrados.csv");
            ficherosEscaneados = logicaMetodos.escanearFicherosPorTamanio(opcionEscogida, rutaSeleccionada);
            System.out.println("------------------------------");
            JOptionPane.showMessageDialog(this, "Ficheros borrados");
            rellenarTablaFicheros();
        }
    }//GEN-LAST:event_jButtonBorrarSeleccionadosActionPerformed

    private void jButtonBorradoAbsolutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonBorradoAbsolutoActionPerformed
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea eliminar todos los ficheros?", "Eliminar ficheros", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {
            logicaMetodos.borradoDeFicheros(ficherosEscaneados, "FicherosBorrados.csv");
            ficherosEscaneados = logicaMetodos.escanearFicherosPorTamanio(opcionEscogida, rutaSeleccionada);
            System.out.println("------------------------------");
            JOptionPane.showMessageDialog(this, "Ficheros borrados");
            rellenarTablaFicheros();
        }
    }//GEN-LAST:event_jButtonBorradoAbsolutoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonBorradoAbsoluto;
    private javax.swing.JButton jButtonBorrarSeleccionados;
    private javax.swing.JButton jButtonEscanear;
    private javax.swing.JComboBox<String> jComboBoxTamanios;
    private javax.swing.JLabel jLabelLimpieza;
    private javax.swing.JLabel jLabelTamanio;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableFichero;
    private javax.swing.JToggleButton jToggleButtonCerrar;
    // End of variables declaration//GEN-END:variables
}
