/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.LogicaMetodos;
import Controlador.GestionCsv;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;

/**
 *
 * @author zapia
 */
public class PantallaEscaneo extends javax.swing.JDialog {

    private LogicaMetodos logicaMetodos = new LogicaMetodos();
    private GestionCsv gestionCsv = new GestionCsv();

    /**
     * Creates new form PantallaEscaneo
     *
     * @param parent
     * @param modal
     */
    public PantallaEscaneo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DefaultComboBoxModel unidades = new DefaultComboBoxModel(logicaMetodos.obtenerParticiones());
        jComboBoxUnidad.setModel(unidades);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboBoxUnidad = new javax.swing.JComboBox<>();
        jButtonEspacioLibre = new javax.swing.JButton();
        jButtonEscanear = new javax.swing.JButton();
        jButtonTamanno = new javax.swing.JButton();
        jButtonLimpiezaTipo = new javax.swing.JButton();
        jButtonDirectoriosVacios = new javax.swing.JButton();
        jButtonLimpiezaDuplicados = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonLimpiezaArchivosAntiguos = new javax.swing.JButton();
        jLabelExplicacionGlobal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Limpieza de disco duro");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Unidad");

        jComboBoxUnidad.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBoxUnidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxUnidadActionPerformed(evt);
            }
        });

        jButtonEspacioLibre.setText("Ver espacio libre");
        jButtonEspacioLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspacioLibreActionPerformed(evt);
            }
        });

        jButtonEscanear.setText("Escanear unidad");
        jButtonEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscanearActionPerformed(evt);
            }
        });

        jButtonTamanno.setText("Limpieza de archivos por tamaño");
        jButtonTamanno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamannoActionPerformed(evt);
            }
        });

        jButtonLimpiezaTipo.setText("Limpieza de archivos por tipo");
        jButtonLimpiezaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiezaTipoActionPerformed(evt);
            }
        });

        jButtonDirectoriosVacios.setText("Limpieza de directorios vacios");
        jButtonDirectoriosVacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectoriosVaciosActionPerformed(evt);
            }
        });

        jButtonLimpiezaDuplicados.setText("Limpieza de archivos duplicados");
        jButtonLimpiezaDuplicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiezaDuplicadosActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jButtonLimpiezaArchivosAntiguos.setText("Limpieza de archivos antiguos");
        jButtonLimpiezaArchivosAntiguos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiezaArchivosAntiguosActionPerformed(evt);
            }
        });

        jLabelExplicacionGlobal.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabelExplicacionGlobal.setForeground(new java.awt.Color(153, 153, 153));
        jLabelExplicacionGlobal.setText("Escoge la unidad que quieres limpiar y que opción quieres utilizar");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBoxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonLimpiezaArchivosAntiguos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpiezaDuplicados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDirectoriosVacios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpiezaTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTamanno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEscanear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEspacioLibre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 148, Short.MAX_VALUE)
                        .addComponent(jButtonCerrar)
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelExplicacionGlobal)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBoxUnidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelExplicacionGlobal)
                .addGap(9, 9, 9)
                .addComponent(jButtonEspacioLibre)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonEscanear)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonTamanno)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpiezaTipo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonLimpiezaArchivosAntiguos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButtonDirectoriosVacios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiezaDuplicados)
                    .addComponent(jButtonCerrar))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxUnidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxUnidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxUnidadActionPerformed

    private void jButtonEspacioLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspacioLibreActionPerformed
        JOptionPane.showMessageDialog(this, logicaMetodos.espacioLibreDisponible(jComboBoxUnidad.getSelectedItem().toString()) + " GB disponibles");

    }//GEN-LAST:event_jButtonEspacioLibreActionPerformed

    private void jButtonEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscanearActionPerformed

        try {
            gestionCsv.grabarFicheroCSV("FileScan.csv", logicaMetodos.listarArchivosRecursivamente(jComboBoxUnidad.getSelectedItem().toString()));
            System.out.println("Listado de archivos guardados en \"FileScan.csv\"");
        } catch (ParseException ex) {
            Logger.getLogger(PantallaEscaneo.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IOException ex) {
            Logger.getLogger(PantallaEscaneo.class.getName()).log(Level.SEVERE, null, ex);
        }


    }//GEN-LAST:event_jButtonEscanearActionPerformed

    private void jButtonTamannoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamannoActionPerformed
        LimpiezaPorTamanio pantallaLimpiezaTamanio = new LimpiezaPorTamanio(this, true, logicaMetodos, jComboBoxUnidad.getSelectedItem().toString());
        pantallaLimpiezaTamanio.setVisible(true);
    }//GEN-LAST:event_jButtonTamannoActionPerformed

    private void jButtonLimpiezaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiezaTipoActionPerformed
        LimpiezaPorTipo limpiezaPorTipo = new LimpiezaPorTipo(this, true, logicaMetodos, jComboBoxUnidad.getSelectedItem().toString());
        limpiezaPorTipo.setVisible(true);
    }//GEN-LAST:event_jButtonLimpiezaTipoActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonLimpiezaArchivosAntiguosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiezaArchivosAntiguosActionPerformed
        LimpiezaPorFecha limpiezaPorFecha = new LimpiezaPorFecha(this, true, logicaMetodos, jComboBoxUnidad.getSelectedItem().toString());
        limpiezaPorFecha.setVisible(true);
    }//GEN-LAST:event_jButtonLimpiezaArchivosAntiguosActionPerformed

    private void jButtonDirectoriosVaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectoriosVaciosActionPerformed
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea eliminar los directorios vacios?", "Eliminar directorios vacios", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {

            logicaMetodos.borradoDeDirectoriosVacios(logicaMetodos.listarArchivosRecursivamente(jComboBoxUnidad.getSelectedItem().toString()));
            //Se vuelve a utilizar el metodo para comprobar que borra todos
            logicaMetodos.borradoDeDirectoriosVacios(logicaMetodos.listarArchivosRecursivamente(jComboBoxUnidad.getSelectedItem().toString()));
            JOptionPane.showMessageDialog(this, "Borrados con exito los directorios vacios.");
        }
    }//GEN-LAST:event_jButtonDirectoriosVaciosActionPerformed

    private void jButtonLimpiezaDuplicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiezaDuplicadosActionPerformed
        LimpiezaArchivosDuplicados limpiezaArchivosDuplicados = new LimpiezaArchivosDuplicados(this, true, logicaMetodos, jComboBoxUnidad.getSelectedItem().toString());
        limpiezaArchivosDuplicados.setVisible(true);
    }//GEN-LAST:event_jButtonLimpiezaDuplicadosActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonDirectoriosVacios;
    private javax.swing.JButton jButtonEscanear;
    private javax.swing.JButton jButtonEspacioLibre;
    private javax.swing.JButton jButtonLimpiezaArchivosAntiguos;
    private javax.swing.JButton jButtonLimpiezaDuplicados;
    private javax.swing.JButton jButtonLimpiezaTipo;
    private javax.swing.JButton jButtonTamanno;
    private javax.swing.JComboBox<String> jComboBoxUnidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelExplicacionGlobal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
