/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaz;

import Controlador.LogicaMetodos;
import Controlador.GestionCsv;
import java.awt.Image;
import java.awt.Toolkit;
import java.io.File;
import java.io.IOException;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author zapia
 */
public class PantallaEscaneo extends javax.swing.JDialog {

    private LogicaMetodos logicaMetodos = new LogicaMetodos();
    private GestionCsv gestionCsv = new GestionCsv();
    private File rutaEscogida;

    /**
     * Creates new form PantallaEscaneo
     *
     * @param parent
     * @param modal
     */
    public PantallaEscaneo(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        DefaultComboBoxModel unidades = new DefaultComboBoxModel(logicaMetodos.obtenerParticiones());

        ImageIcon myImage = new ImageIcon(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/Interfaz/img/hdimg.png")));
        Image img1 = myImage.getImage();
        Image img2 = img1.getScaledInstance(jLabelDisk.getWidth(), jLabelDisk.getHeight(), Image.SCALE_SMOOTH);
        ImageIcon i = new ImageIcon(img2);
        jLabelDisk.setIcon(i);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButtonEspacioLibre = new javax.swing.JButton();
        jButtonEscanear = new javax.swing.JButton();
        jButtonTamanno = new javax.swing.JButton();
        jButtonLimpiezaTipo = new javax.swing.JButton();
        jButtonDirectoriosVacios = new javax.swing.JButton();
        jButtonLimpiezaDuplicados = new javax.swing.JButton();
        jButtonCerrar = new javax.swing.JButton();
        jButtonLimpiezaArchivosAntiguos = new javax.swing.JButton();
        jLabelExplicacionGlobal = new javax.swing.JLabel();
        jLabelDisk = new javax.swing.JLabel();
        jButtonComprimir = new javax.swing.JButton();
        jButtonEscogeCarpeta = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 102, 102));
        jLabel1.setText("Limpieza de disco duro");

        jLabel2.setForeground(new java.awt.Color(102, 102, 102));
        jLabel2.setText("Unidad");

        jButtonEspacioLibre.setText("Ver espacio libre");
        jButtonEspacioLibre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEspacioLibreActionPerformed(evt);
            }
        });

        jButtonEscanear.setText("Escanear unidad");
        jButtonEscanear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscanearActionPerformed(evt);
            }
        });

        jButtonTamanno.setText("Limpieza de archivos por tamaño");
        jButtonTamanno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonTamannoActionPerformed(evt);
            }
        });

        jButtonLimpiezaTipo.setText("Limpieza de archivos por tipo");
        jButtonLimpiezaTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiezaTipoActionPerformed(evt);
            }
        });

        jButtonDirectoriosVacios.setText("Limpieza de directorios vacios");
        jButtonDirectoriosVacios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDirectoriosVaciosActionPerformed(evt);
            }
        });

        jButtonLimpiezaDuplicados.setText("Limpieza de archivos duplicados");
        jButtonLimpiezaDuplicados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiezaDuplicadosActionPerformed(evt);
            }
        });

        jButtonCerrar.setText("Cerrar");
        jButtonCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCerrarActionPerformed(evt);
            }
        });

        jButtonLimpiezaArchivosAntiguos.setText("Limpieza de archivos antiguos");
        jButtonLimpiezaArchivosAntiguos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLimpiezaArchivosAntiguosActionPerformed(evt);
            }
        });

        jLabelExplicacionGlobal.setFont(new java.awt.Font("Dialog", 1, 10)); // NOI18N
        jLabelExplicacionGlobal.setForeground(new java.awt.Color(153, 153, 153));
        jLabelExplicacionGlobal.setText("Escoge la unidad que quieres limpiar y que opción quieres utilizar");

        jButtonComprimir.setText("Comprimir carpeta");
        jButtonComprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonComprimirActionPerformed(evt);
            }
        });

        jButtonEscogeCarpeta.setText("...");
        jButtonEscogeCarpeta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonEscogeCarpetaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButtonEscogeCarpeta, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabelExplicacionGlobal)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jButtonLimpiezaArchivosAntiguos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpiezaDuplicados, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonDirectoriosVacios, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonLimpiezaTipo, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonTamanno, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEscanear, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButtonEspacioLibre, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jButtonCerrar))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(39, 39, 39)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jButtonComprimir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabelDisk, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE)))))
                        .addGap(38, 38, 38))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jButtonEscogeCarpeta))
                .addGap(11, 11, 11)
                .addComponent(jLabelExplicacionGlobal)
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jButtonEspacioLibre)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonEscanear)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonTamanno)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiezaTipo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonLimpiezaArchivosAntiguos))
                    .addComponent(jLabelDisk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonDirectoriosVacios)
                    .addComponent(jButtonComprimir))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonLimpiezaDuplicados)
                    .addComponent(jButtonCerrar))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonEspacioLibreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEspacioLibreActionPerformed
        if (rutaEscogida == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ruta", "Selecciona ruta", JOptionPane.ERROR_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(this, logicaMetodos.espacioLibreDisponible(rutaEscogida.toString()) + " GB disponibles");
        }
    }//GEN-LAST:event_jButtonEspacioLibreActionPerformed

    private void jButtonEscanearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscanearActionPerformed
        if (rutaEscogida == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ruta", "Selecciona ruta", JOptionPane.ERROR_MESSAGE);
        } else {
            try {
                gestionCsv.grabarFicheroCSV("FileScan.csv", logicaMetodos.listarArchivosRecursivamente(rutaEscogida.toString()));
                System.out.println("Listado de archivos guardados en \"FileScan.csv\"");
            } catch (ParseException ex) {
                Logger.getLogger(PantallaEscaneo.class.getName()).log(Level.SEVERE, null, ex);
            } catch (IOException ex) {
                Logger.getLogger(PantallaEscaneo.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButtonEscanearActionPerformed

    private void jButtonTamannoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonTamannoActionPerformed
        if (rutaEscogida == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ruta", "Selecciona ruta", JOptionPane.ERROR_MESSAGE);
        } else {
            LimpiezaPorTamanio pantallaLimpiezaTamanio = new LimpiezaPorTamanio(this, true, logicaMetodos, rutaEscogida.toString());
            pantallaLimpiezaTamanio.setVisible(true);
        }
    }//GEN-LAST:event_jButtonTamannoActionPerformed

    private void jButtonLimpiezaTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiezaTipoActionPerformed
        if (rutaEscogida == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ruta", "Selecciona ruta", JOptionPane.ERROR_MESSAGE);
        } else {
            LimpiezaPorTipo limpiezaPorTipo = new LimpiezaPorTipo(this, true, logicaMetodos, rutaEscogida.toString());
            limpiezaPorTipo.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLimpiezaTipoActionPerformed

    private void jButtonCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCerrarActionPerformed
        dispose();
    }//GEN-LAST:event_jButtonCerrarActionPerformed

    private void jButtonLimpiezaArchivosAntiguosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiezaArchivosAntiguosActionPerformed
        if (rutaEscogida == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ruta", "Selecciona ruta", JOptionPane.ERROR_MESSAGE);
        } else {
            LimpiezaPorFecha limpiezaPorFecha = new LimpiezaPorFecha(this, true, logicaMetodos, rutaEscogida.toString());
            limpiezaPorFecha.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLimpiezaArchivosAntiguosActionPerformed

    private void jButtonDirectoriosVaciosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDirectoriosVaciosActionPerformed
        int valor = JOptionPane.showConfirmDialog(this, "¿Desea eliminar los directorios vacios?", "Eliminar directorios vacios", JOptionPane.YES_NO_OPTION);
        if (valor == JOptionPane.YES_OPTION) {

            logicaMetodos.borradoDeDirectoriosVacios(logicaMetodos.listarArchivosRecursivamente(rutaEscogida.toString()));
            //Se vuelve a utilizar el metodo para comprobar que borra todos
            logicaMetodos.borradoDeDirectoriosVacios(logicaMetodos.listarArchivosRecursivamente(rutaEscogida.toString()));
            JOptionPane.showMessageDialog(this, "Borrados con exito los directorios vacios.");
        }
    }//GEN-LAST:event_jButtonDirectoriosVaciosActionPerformed

    private void jButtonLimpiezaDuplicadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLimpiezaDuplicadosActionPerformed
        if (rutaEscogida == null) {
            JOptionPane.showMessageDialog(this, "No has seleccionado ninguna ruta", "Selecciona ruta", JOptionPane.ERROR_MESSAGE);
        } else {
            LimpiezaArchivosDuplicados limpiezaArchivosDuplicados = new LimpiezaArchivosDuplicados(this, true, logicaMetodos, rutaEscogida.toString());
            limpiezaArchivosDuplicados.setVisible(true);
        }
    }//GEN-LAST:event_jButtonLimpiezaDuplicadosActionPerformed

    private void jButtonComprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonComprimirActionPerformed
        ComprimirCarpetas comprimirCarpetas = new ComprimirCarpetas(this, true, logicaMetodos);
        comprimirCarpetas.setVisible(true);
    }//GEN-LAST:event_jButtonComprimirActionPerformed

    private void jButtonEscogeCarpetaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonEscogeCarpetaActionPerformed

        rutaEscogida = logicaMetodos.escogerDirectorio(this);
    }//GEN-LAST:event_jButtonEscogeCarpetaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCerrar;
    private javax.swing.JButton jButtonComprimir;
    private javax.swing.JButton jButtonDirectoriosVacios;
    private javax.swing.JButton jButtonEscanear;
    private javax.swing.JButton jButtonEscogeCarpeta;
    private javax.swing.JButton jButtonEspacioLibre;
    private javax.swing.JButton jButtonLimpiezaArchivosAntiguos;
    private javax.swing.JButton jButtonLimpiezaDuplicados;
    private javax.swing.JButton jButtonLimpiezaTipo;
    private javax.swing.JButton jButtonTamanno;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabelDisk;
    private javax.swing.JLabel jLabelExplicacionGlobal;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
